### ISSUE TITLE
Enhance GitHub Actions Workflow for SBOM and Security Reports

### ISSUE THREAD

**Issue by sanmarg** [SBOMgen/SBOM-Automation#1]
As we continue to refine our CI/CD pipeline, it's essential to optimize our GitHub Actions workflow for generating Software Bill of Materials (SBOM) and security reports. To streamline the process and enhance readability, I propose combining the PDF generation and upload steps into a single step.

By assigning this task to me, I will take ownership of implementing the proposed enhancements to the GitHub Actions workflow. This optimization will improve the efficiency and clarity of our CI/CD process, contributing to a smoother development experience.

Looking forward to tackling this task and improving our workflow.

**Comment by dvjsharma** [comment]
What benefit may this serve?
